categories:
  - title: 'Features'
    labels:
      - 'feature'
  - title: 'Enhancement'
    labels:
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bugfix'
  - title: 'Documentation'
    labels:
      - 'docs'
      - 'style'
  - title: 'Infrastructure'
    labels:
      - 'refactor'
      - 'chore'
      - 'test'
      - 'build'
      
autolabeler:
  - label: 'feature'
    title:
      - '/feat:/i'
  - label: 'chore'
    title:
      - '/chore:/i'
    files:
      - '*.md'
      - '*.txt'
      - '*.yml'
  - label: 'bugfix'
    title:
      - '/fix:/i'
  - label: 'enhancement'
    title:
      - '/enh:/i'
    body:
      - '/JIRA-[0-9]{1,4}/'

exclude-labels:
  - 'skip-changelog'

template: |
  ## Changelog
  $CHANGES
