name: Release change log generator

on:
  push:
    branches:
      - main
      - stable
  pull_request:
    types: [opened, reopened, synchronize]
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
      
    runs-on: ubuntu-latest
    
    steps:
      - uses: release-drafter/release-drafter@v6.0.0
        with:
            config-name: release-drafter.yml
            disable-autolabeler: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
