name: jamovi-builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build jamovi
        run: |
            git clone https://github.com/jamovi/jamovi.git
            cd jamovi
            git submodule update --init --recursive
            docker-compose build
