name: 'Build JASP desktop'

on:
   push:

jobs:
      
   build-jasp:
   
    runs-on: ubuntu-latest
    name:  deb build on ubuntu-latest
        
    steps:
      - uses: actions/checkout@v3
      
      - uses: r-lib/actions/setup-r@v2
           
      - name: Test Rtools installation
        run: |
           install.packages("jsonlite", type = "source")
        shell: Rscript {0}

      - name: Install Qt6
        uses: jurplel/install-qt-action@v3
        with:
            version: 6.4.*
           
      - name: Install dependencies of build system
        run: |
            sudo apt install libboost-dev libjsoncpp25 libjsoncpp-dev libarchive13 libarchive-dev
            sudo apt install libxcb-xkb-dev libxcb-xkb1 libxcb-xinerama0 libxkbcommon-dev libxkbcommon-x11-dev autoconf zlib1g zlib1g-dev cmake
            sudo apt install gfortran build-essential flex libssl-dev libgl1-mesa-dev libsqlite3-dev r-base
        
      - name: Get JASP desktop repo
        run: |
            git clone https://github.com/jasp-stats/jasp-desktop.git
            echo cd jasp-desktop
            
