name: 'Build JASP desktop'

on:
   push:
     paths: ['**/JASP*.yml']

jobs:
      
   build-jasp:
   
    runs-on: ubuntu-latest
    env:
       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
       
    name:  deb build on ubuntu-latest
        
    steps:
      - uses: actions/checkout@v3
      
      - uses: r-lib/actions/setup-r@v2
           
      - name: Test Rtools installation
        run: |
           install.packages("jsonlite", type = "source")
        shell: Rscript {0}

      - name: Install Qt6
        uses: jurplel/install-qt-action@v3
        with:
            version: 6.4.*
           
      - name: Install boost library
        run: |
            wget https://boostorg.jfrog.io/artifactory/main/release/1.82.0/source/boost_1_82_0.tar.gz
            tar -xzf boost_*.tar.gz && cd boost_*/
            ./bootstrap.sh
            ./b2 install
            
      - name: Install dependencies of build system
        run: |     
            sudo apt install libboost-dev libjsoncpp25 libjsoncpp-dev libarchive13 libarchive-dev
            sudo apt install libxcb-xkb-dev libxcb-xkb1 libxcb-xinerama0 libxkbcommon-dev libxkbcommon-x11-dev autoconf zlib1g zlib1g-dev cmake
            sudo apt install gfortran build-essential flex libssl-dev libgl1-mesa-dev libsqlite3-dev r-base

      - name: Install Readstat
        run: |
            wget https://github.com/WizardMac/ReadStat/releases/download/v1.1.9/readstat-1.1.9.tar.gz
            tar -xzf readstat-*.tar.gz && cd readstat-*/
            ./configure
            make
            sudo make install
        
      - name: Build JASP desktop
        run: |
            git clone  https://github.com/jasp-stats/jasp-desktop.git
            cmake -S ./jasp-desktop -B ./jasp-release
            cmake -build ./jasp-release --target all
            
