name: 'mingw64 environment'

on:
  push:
    branches:
       - main
       - dev
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    
    env:
       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
    steps:
      - uses: actions/checkout@v3
      
      - name: Install MinGW
        uses: egor-tensin/setup-mingw@v2.2.0
        
      - name: Build ReadStat
        run: |
              wget https://github.com/WizardMac/ReadStat/releases/download/v1.1.9/readstat-1.1.9.tar.gz
              tar xvf readstat-1.1.9.tar.gz
              cd readstat-1.1.9
              # export CFLAGS=-Wno-error; export CXXFLAGS=-Wno-error; # I couldnt build 1.1.7 nor 1.1.8 without setting these
              ./configure
              make -j
              make install
